version: 2
jobs:
  PIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "System"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/platformio/platformio/archive/develop.zip
      - run:
          name: "Build"
          command: |
            platformio run -d .

  QIO:
    docker:
      - image: python:3
    steps:
      - checkout
      - run:
          name: "System"
          command: |
            apt update
            apt install -y git
            git submodule update --init --recursive
      - run:
          name: "Install"
          command: |
            python -m pip install --upgrade pip
            pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
            qio platform install https://github.com/OS-Q/P511/archive/master.zip
      - run:
          name: "Build"
          command: |
            qio run -d .

workflows:
    version: 2
    run_ci:
        jobs:
            - PIO
            - QIO
